#!/usr/bin/env bash
# 

load="$(cut -d ' ' -f1 /proc/loadavg)"
cpus="$(nproc)"

# full text
echo " $load"

# short text
echo " $load"

if [ $(bc <<< "$load >= 2.0") -gt 0 ]; then
    echo "#f00000"
elif [ $(bc <<< "$load >= 0.9") -gt 0 ]; then
    echo "#d75f00"
fi

